/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.polymorphism;

/**
 *
 * @author PC
 */
public class GradeCalculation extends javax.swing.JFrame {

    /**
     * Creates new form GradeCalculation
     */
    public GradeCalculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrelimTextField = new javax.swing.JTextField();
        PrelimLabel = new javax.swing.JLabel();
        MidtermLabel = new javax.swing.JLabel();
        MidtermTextField = new javax.swing.JTextField();
        SemiFinalLabel = new javax.swing.JLabel();
        SemiFinalTextField = new javax.swing.JTextField();
        FinalLabel = new javax.swing.JLabel();
        FInalTextField = new javax.swing.JTextField();
        ComputeAverageButton = new javax.swing.JButton();
        ComputePercentageButton = new javax.swing.JButton();
        GradeLabel = new javax.swing.JLabel();
        GradeTextField = new javax.swing.JTextField();
        RemarksLabel = new javax.swing.JLabel();
        RemarksTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrelimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrelimTextFieldActionPerformed(evt);
            }
        });

        PrelimLabel.setText("Prelim");

        MidtermLabel.setText("Midterm");

        MidtermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MidtermTextFieldActionPerformed(evt);
            }
        });

        SemiFinalLabel.setText("Semi Final");

        SemiFinalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemiFinalTextFieldActionPerformed(evt);
            }
        });

        FinalLabel.setText("Final");

        FInalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FInalTextFieldActionPerformed(evt);
            }
        });

        ComputeAverageButton.setText("COMPUTE BASED ON AVERAGE");
        ComputeAverageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeAverageButtonActionPerformed(evt);
            }
        });

        ComputePercentageButton.setText("COMPUTE BASED ON PERCENTAGE");
        ComputePercentageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputePercentageButtonActionPerformed(evt);
            }
        });

        GradeLabel.setText("GRADE");

        GradeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeTextFieldActionPerformed(evt);
            }
        });

        RemarksLabel.setText("REMARKS");

        RemarksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemarksTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RemarksLabel)
                    .addComponent(GradeLabel)
                    .addComponent(FinalLabel)
                    .addComponent(SemiFinalLabel)
                    .addComponent(MidtermLabel)
                    .addComponent(PrelimLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComputePercentageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(ComputeAverageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrelimTextField)
                    .addComponent(MidtermTextField)
                    .addComponent(SemiFinalTextField)
                    .addComponent(FInalTextField)
                    .addComponent(GradeTextField)
                    .addComponent(RemarksTextField))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrelimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrelimLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MidtermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MidtermLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemiFinalLabel)
                    .addComponent(SemiFinalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalLabel)
                    .addComponent(FInalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ComputeAverageButton)
                .addGap(18, 18, 18)
                .addComponent(ComputePercentageButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradeLabel)
                    .addComponent(GradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemarksLabel)
                    .addComponent(RemarksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrelimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrelimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrelimTextFieldActionPerformed

    private void MidtermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MidtermTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MidtermTextFieldActionPerformed

    private void SemiFinalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemiFinalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemiFinalTextFieldActionPerformed

    private void FInalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FInalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FInalTextFieldActionPerformed

    private void ComputeAverageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeAverageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComputeAverageButtonActionPerformed

    private void ComputePercentageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputePercentageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComputePercentageButtonActionPerformed

    private void GradeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeTextFieldActionPerformed

    private void RemarksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemarksTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemarksTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComputeAverageButton;
    private javax.swing.JButton ComputePercentageButton;
    private javax.swing.JTextField FInalTextField;
    private javax.swing.JLabel FinalLabel;
    private javax.swing.JLabel GradeLabel;
    private javax.swing.JTextField GradeTextField;
    private javax.swing.JLabel MidtermLabel;
    private javax.swing.JTextField MidtermTextField;
    private javax.swing.JLabel PrelimLabel;
    private javax.swing.JTextField PrelimTextField;
    private javax.swing.JLabel RemarksLabel;
    private javax.swing.JTextField RemarksTextField;
    private javax.swing.JLabel SemiFinalLabel;
    private javax.swing.JTextField SemiFinalTextField;
    // End of variables declaration//GEN-END:variables
}
